### ISSUE TITLE
Authentication Support for Huggingface Models

### ISSUE THREAD

**Issue by HelenaCreates** [lucataco/cog-flux-schnell-lora#2]
Hi Luis,
thank you for the amazing scripts!

Do you think you could add authentication for huggingface models? I have set my repository to private for obvious reasons, but now the script doesn't work.
I get the following error:
```
Prediction failed.

401 Client Error. (Request ID: Root=1-66c69cfe-4965f01c1dc1f6856fbaad65;cbf16671-470f-4a03-94c4-7006e34bf5b6) Repository Not Found for url: https://huggingface.co/api/models/HelenaQ/Helena-lora. Please make sure you specified the correct `repo_id` and `repo_type`. If you are trying to access a private or gated repo, make sure you are authenticated. Invalid username or password.
```
Maybe there is a way to add authentication to this line https://github.com/lucataco/cog-flux-schnell-lora/blob/master/predict.py#L159

Thanks again for this amazing model!!
Best, Helena

**Comment by lucataco** [comment]
You're welcome!
Feel free to remix the model and push out your own implementation on Replicate
Here's some documentation on [working with secret inputs for models](https://replicate.com/changelog/2024-06-07-secret-inputs-for-models)
