### ISSUE TITLE
is there any way to run this locally like an api with own gpu instead of using replicate ?

### ISSUE THREAD

**Issue by analogpvt** [lucataco/cog-flux-schnell-lora#3]
like using my own gpu or aws or google cloud gpu to make it faster

**Comment by lucataco** [comment]
Yes you can run [Cog](https://github.com/replicate/cog) locally to use your own GPU
Run with: `cog predict -i prompt="a beautiful castle frstingln illustration" -hf_lora="alvdansen/frosting_lane_flux"`
