### ISSUE TITLE
Some requests regarding custom LoRA path

### ISSUE THREAD

**Issue by hourianto** [lucataco/cog-flux-schnell-lora#4]
Would it be possible to improve the path handling for LoRAs to accept more paths?

Some LoRAs on HuggingFace don't have the same lora name as the repository -  https://huggingface.co/alfredplpl/flux.1-dev-modern-anime-lora for example. I guess a solution for this case would be to handle HF direct download links like `https://huggingface.co/alfredplpl/flux.1-dev-modern-anime-lora/resolve/main/modern-anime-lora.safetensors` in the same way they're handled for other platforms?

**Comment by noahy67** [comment]
I believe the issue has to do with a "." in the huggingface model name, as the error logs claim that a certain model is not found, however it does not properly parse the full model name and stops at the first "."

A fix to the Regex would be greatly appreciated

**Comment by lucataco** [comment]
Try out the new official flux-schnell-lora model here: [black-forest-labs/flux-schnell-lora](https://replicate.com/black-forest-labs/flux-schnell-lora)
