### ISSUE TITLE
Some LoRAs (especially from CivitAI) do not get applied for some reason

### ISSUE THREAD

**Issue by hourianto** [lucataco/cog-flux-schnell-lora#6]
(This is written for Flux dev (https://replicate.com/lucataco/flux-dev-lora), but I think it should apply to the Schnell version as well.)

It seems like a lot of Flux LoRAs from CivitAI do not work. I think this might apply to LoRAs that were not trained on Replicate or something, maybe they have different layer names?

Here are some models for you to try:
- [Kalin Flux LoRA](https://civitai.com/models/676814/flux-lora-kalin-style?modelVersionId=757639) - needs login to be downloaded, here's a link to download or use it directly with the explorer: `https://files.catbox.moe/gcn2yy.safetensors` (you can of course otherwise just add &token with your API token to the CivitAI link). If you use the LoRA on the dev explorer with a prompt like `by lolita_impasto_style, an anime girl is standing in a library` it'll not work (and change the style in a very obvious way) and instead just give you the "default" Flux look. Here's an example image with that prompt when the LoRA _does_ get applied (tested on CivitAI itself): 
![image](https://github.com/user-attachments/assets/26ae0c4e-02db-4a1a-bf8f-8c985ff3ee23).

- [Wasabi flux](https://civitai.com/models/651603/wasabi-flux-style?modelVersionId=728975) - link for the lora explorer: `https://civitai.com/api/download/models/728975?type=Model&format=SafeTensor`. It doesn't have a trigger word. Same result, if the LoRA is applied you get that style, otherwise it's the generic Flux anime style.
![image](https://github.com/user-attachments/assets/03b13f1f-48e5-4174-9a4c-ba55dc9b636a)

I'm honestly not sure whether the issue is somewhere in the code of this repo or in Transformers, maybe it's because the version of the Transformers that the image is using is outdated and Transformers only started supporting those loras more recently?

**Comment by lucataco** [comment]
If the CivitAI LoRA is gated by sign-in access, be sure to add your CivitAI API token at the end of the URL: 
`&token=<YOUR_API_TOKEN>`

**Comment by hourianto** [comment]
@lucataco I know, I brought that up in the first lora example, my point was that the lora doesn't get applied even though the file is downloaded successfully in the logs. Only some loras don't work. I was wondering if the lora code that this implementation uses doesn't support some flux lora types, perhaps the ones that were trained on CivitAI directly? I'm not sure, really.
