### ISSUE TITLE
Img2Img strength not working

### ISSUE THREAD

**Issue by ericmillsio** [lucataco/cog-flux-schnell-lora#7]
The prompt strength has a weird cliff at 75 where <=75 you basically get close to the same image, and >75 you get something completely different. Seems to happen with or without the LORA. 

Could be: a bug, maybe needs a different scheduler or shift value, or just a flaw of forcing Schnell to do img2img? DrawThings does seem to work for Schnell img2img without this issue though. Anyway just some thoughts.

Couple examples:

76: https://replicate.com/p/925wwp9gqdrj00cjte9rt06bec
75: https://replicate.com/p/cp7rnecaxxrj60cjte9vdk06sm

Thanks for putting this together!

**Comment by lucataco** [comment]
Flux Schnell model that BFL released isn’t a model that supports img2img. 
I added it so people can try it out for themselves
